FROM golang:alpine AS build

RUN mkdir /src
COPY go.mod /src
COPY main.go /src

WORKDIR /src
RUN go get -d -v 
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/bin/apitest

FROM scratch AS final

COPY --from=build /go/bin/apitest /apitest

ENTRYPOINT ["/apitest"]
