kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webby
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - psp-webby
#- apiGroups: [""] # "" indicates the core API group
#  resources: ["pods"]
#  verbs: ["get", "watch", "list"]