apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-webby
spec:
  hostPID: false
  hostNetwork: false
  hostIPC: false
  privileged: false  # Prevents creation of privileged Pods
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - NET_BIND_SERVICE
  runAsUser:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MayRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  volumes:
  - '*'