apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-unrestricted
spec:
  hostPID: true
  hostNetwork: true
  hostIPC: true
  privileged: true  # Prevents creation of privileged Pods
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'