apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverlab-web
  namespace: serverlab
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serverlab-web
  template:
    metadata:
      labels:
        app: serverlab-web
    spec:
      serviceAccount: serverlab-web
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverlab-web-dev
  namespace: serverlab
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serverlab-web-dev
  template:
    metadata:
      labels:
        app: serverlab-web-dev
    spec:
      serviceAccount: serverlab-web-dev
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.18
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverlab-web-prod
  namespace: serverlab
  labels:
    app: serverlab-web-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serverlab-web-prod
  template:
    metadata:
      labels:
        app: serverlab-web-prod
    spec:
      serviceAccount: serverlab-web-prod
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.18
        ports:
        - containerPort: 80