apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: serverlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-restricted
subjects:
# Example: All service accounts in my-namespace
#- apiGroup: rbac.authorization.k8s.io
#  kind: Group
#  name: system:serviceaccounts
# Example: A specific service account in my-namespace
- kind: ServiceAccount # Omit apiGroup
  name: serverlab-web
  namespace: serverlab
- kind: ServiceAccount
  name: serverlab-web-dev
- kind: ServiceAccount
  name: serverlab-web-prod