apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nonpriv
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccount: nginx-privileged-sa
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webby-priv
  name: webby-priv
  namespace: nonpriv
  #annotations:
    # container.security.alpha.kubernetes.io/pod: "runtime/default" ### All Pod containers
    # container.security.alpha.kubernetes.io/webby-priv: "runtime/default" ### Container specific
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webby-priv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webby-priv
    spec:
      containers:
      - image: gcr.io/serverlab/webby:0.1.4-scratch
        name: webby-priv
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webby-nonpriv
  name: webby-nonpriv
  namespace: nonpriv
  #annotations:
    # container.security.alpha.kubernetes.io/pod: "runtime/default" ### All Pod containers
    # container.security.alpha.kubernetes.io/webby-priv: "runtime/default" ### Container specific
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webby-nonpriv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webby-nonpriv
    spec:
      securityContext:
        runAsUser: 30000
        runAsGroup: 30000
        fsGroup: 30000
      containers:
      - image: gcr.io/serverlab/webby:0.1.4-scratch-nonpriv
        name: webby-nonpriv
        env:
          - name: PORT
            value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webby-netcap
  name: webby-netcap
  namespace: nonpriv
  #annotations:
    # container.security.alpha.kubernetes.io/pod: "runtime/default" ### All Pod containers
    # container.security.alpha.kubernetes.io/webby-priv: "runtime/default" ### Container specific
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webby-netcap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webby-netcap
    spec:
      securityContext:
        runAsUser: 30000
        runAsGroup: 30000
        fsGroup: 30000
      containers:
      - image: gcr.io/serverlab/webby:0.1.4-scratch-cap
        name: webby-netcap
        ports:
        - containerPort: 80
          protocol: TCP  
